# =========================================
# CONFIGURAÇÃO DO SERVIDOR
# =========================================
server.port=${PORT:8080}

# =========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (MySQL Dinâmico)
# =========================================
# Se houver uma URL na nuvem, usa ela. Senão, usa o localhost.
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/sistema_loja?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# =========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true